### ISSUE TITLE
[4.4.1] Strange pathways in the middle of wall of hollow cylinder on some layers

### ISSUE THREAD

**Issue by LightTemplar** [Ultimaker/CuraEngine#1191] opened 2020-01-29 20:44 UTC
**Application Version**
4.4.1

**Platform**
KDE Neon, Linux

**Steps to Reproduce**
I added an STL with a hollow cylinder as part of it. Sliced and looked layers. 

**Actual Results**
Some layers had no circles in the middle of the round wall, but parallel lines. 

**Expected results**
all pathways on all layers of the hollow cylinder are circular.

**Additional Information**
Wall line count is 4, so it is enough to make all cylinder from walls.
 
Project: https://we.tl/t-WOTjhi49Im
Original STL: https://we.tl/t-tkGnd3l2eb

![image](https://user-images.githubusercontent.com/453783/73393569-30f7b580-42dc-11ea-8f97-4800fad9eef4.png)
![image](https://user-images.githubusercontent.com/453783/73393722-71efca00-42dc-11ea-85dc-393269a92588.png)

**Comment by LightTemplar** [comment] 2020-01-29 20:46
For test purposes I made a simple cylinder. It has a slightly different pattern in the middle, but still has.
Its project: https://we.tl/t-kvHReyehnf
Simple Cylinder STL: https://we.tl/t-vAlkNDiFHX

**Comment by smartavionics** [comment] 2020-01-29 22:52
Unfortunately, the wall gap filling (and thin wall printing) in UM Cura does do what you have observed. It's a known problem. If you wish to try one of my Cura releases which can be found at https://www.dropbox.com/sh/s43vqzmi4d2bqe2/AAADdYdSu9iwcKa0Knqgurm4a?dl=0 you will find that they handle the gap filling with fewer artifacts. Please read the README.md file there for more information. Note that in my latest releases I added some extra options to the gap fill menu. Unfortunately, I goofed and they don't work as I expected but the normal "Everywhere" option does work OK. Here's what I get when I sliced your project.

![Screenshot_2020-01-29_22-47-34](https://user-images.githubusercontent.com/585618/73404684-fbf25f80-42e9-11ea-8468-f7a221e155a4.png)

**Comment by LightTemplar** [comment] 2020-01-30 03:10
Unfortunately, your release is not usable for me, as it has some strange font glitches. And I'm not sure, if it lies within the app, or within my system, because I saw the same problem also with teamviewer. Google didn't help much :(

![image](https://user-images.githubusercontent.com/453783/73416309-cca51800-4314-11ea-8892-7e46b43596d0.png)

**Comment by smartavionics** [comment] 2020-01-30 07:19
That's a shame, it must be because I am building my releases using QT 5.13.2 rather than 5.10 or whatever UM are currently using. I know they are looking at using a more recent version of QT so it could be that their future releases wouldn't work right for you either. Could you please run the AppImage from a terminal window and see if any interesting messages appear there. Thanks.

**Comment by smartavionics** [comment] 2020-01-30 07:46
Could you please open an issue at https://github.com/smartavionics/Cura so we can discuss this font/UI problem.

A quick search found me https://cullmann.io/posts/kde-qt-highdpi-scaling/ maybe it's relevant.

**Comment by smartavionics** [comment] 2020-01-30 07:50
Also, this could be relevant https://doc.qt.io/qt-5/highdpi.html

**Comment by LightTemplar** [comment] 2020-01-30 17:39
Sure thing! https://github.com/smartavionics/Cura/issues/41

**Comment by Ghostkeeper** [comment] 2020-01-31 10:46
Duplicate of https://github.com/Ultimaker/Cura/issues/5110. Since that issue was raised we've made some improvements but it's still a bug. This is an ongoing project for us. Last week we've had a POC implementation brought to us that would fix this issue in a good way. Now we need to make that release-ready. Please continue discussion in the other thread.

**Closed by Ghostkeeper** 2020-01-31 10:46 UTC

**Comment by Ghostkeeper** [comment] 2020-02-03 10:24
By the way from source I'm running Qt 5.13.2 as well, and I'm not having that visual glitch.
