### ISSUE TITLE
Unnecessary retractions and movement

### ISSUE THREAD

**Issue by warbunnies** [Ultimaker/CuraEngine#521] opened 2017-05-23 02:32 UTC
I decided to try out Cura because I had heard good things and I wanted to compare it to my experience with s3d and slic3r. However I am having a major issue with the number of retractions and the order of movements being performed. 

Instead of printing a set of perimeters, it will print one loop then retract and jump and start a different set of perimeters, before coming back to the original perimeter set to finish the second one, then retract again and go do something else. The firmware shouldn't be retracting more than once for a set of perimeters. Attached is a photo, I have turned on coasting so that you can see how it is retracting an absurd amount when it does not need to be. 

The version I am using was downloaded today from the ultimaker website. Is there a setting I can change or is this a glitch?

[Unnecessary-retractions.pdf](https://github.com/Ultimaker/CuraEngine/files/1020727/Unnecessary-retractions.pdf)

Edit: was told attaching the project file as a .txt file would be helpful:
[CFP_MODEL6c-2.curaproject.txt](https://github.com/Ultimaker/CuraEngine/files/1023045/CFP_MODEL6c-2.curaproject.txt)

**Comment by smartavionics** [comment] 2017-05-23 08:14
It just so happens that I am just about to post a PR that attempts to address this issue. It's in it's infancy but looking promising.

**Comment by warbunnies** [comment] 2017-05-23 11:55
Well thats lucky! So has cura always been like that? There are a lot of smart features built in but that seems like something that should have been fixed a long time ago. Either way thanks, I'll definitely test it out.

**Comment by smartavionics** [comment] 2017-05-23 12:01
Hi. I'm a relative newcomer to Cura myself so I don't know if it has always behaved like it does in this regard. To test it you will have to build CuraEngine from the source as I don't know when this will be integrated into the code base.

**Comment by warbunnies** [comment] 2017-05-23 15:05
O... XD I'm working on a dc micro extruder right now so I aint got time to mess around with that. I wish ya luck though!

**Comment by BagelOrb** [comment] 2017-07-23 10:51
Duplicate of https://github.com/Ultimaker/CuraEngine/issues/225

**Closed by BagelOrb** 2017-07-23 10:51 UTC
Labels: enhancement
