### ISSUE TITLE
Useless supports to nowhere/hanging in the air being generated

### ISSUE THREAD

**Issue by mah115** [Ultimaker/CuraEngine#1466] opened 2021-07-12 17:02 UTC
**Application Version**

4.10.0
**Platform**

Windows 10
**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

Slice attached project

**Actual Results**

Support structures that don't support anything and also hanging in mid-air being generated.
**Expected results**

Supports should actually support something
**Additional Information**

![image](https://user-images.githubusercontent.com/2501918/125327519-0e9eff80-e2f8-11eb-9895-9de097da2d7a.png)
![image](https://user-images.githubusercontent.com/2501918/125327546-165ea400-e2f8-11eb-8083-123b528bf7b5.png)
![image](https://user-images.githubusercontent.com/2501918/125327584-2080a280-e2f8-11eb-9664-acafc16f4ca7.png)
![image](https://user-images.githubusercontent.com/2501918/125327710-41e18e80-e2f8-11eb-8b88-af803306f3bd.png)
![image](https://user-images.githubusercontent.com/2501918/125327740-4d34ba00-e2f8-11eb-9161-6eab4f44f9cc.png)
[CFFFP_Fan_Duct v8.zip](https://github.com/Ultimaker/CuraEngine/files/6803173/CFFFP_Fan_Duct.v8.zip)

**Comment by fvrmr** [comment] 2021-07-16 13:15
Hi @mah115 if you change the `support horizontal expansion` and `support interface horizontal expansion` to 0mm those towers are not printed. 
And the support that is generated from mid air, is happening because of the support pattern. A work around for this is to turn your model with the blue axis. 
Let me know if that works for you!

**Comment by Ghostkeeper** [comment] 2021-07-20 14:30
Duplicate of https://github.com/Ultimaker/Cura/issues/7487.

**Closed by Ghostkeeper** 2021-07-20 14:30 UTC
