### ISSUE TITLE
Order of execution when using One at a Time Print sequence

### ISSUE THREAD

**Issue by GingerPaul55** [Ultimaker/CuraEngine#1262] opened 2020-06-03 10:32 UTC
**Application Version**
4.6.1

**Platform**
Linux 5.3.0-55-generic #49-Ubuntu SMP Thu May 21 12:47:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Steps to Reproduce**

1. Add multiple models to Ultimaker Cura, ensure one is smaller and one is larger than the max print height when using One at a Time Print sequence
2. Click the Slice button

**Actual Results**
An error message is shown saying unable to slice.

**Expected results**
A successful slice that I can send to the 3D printer

**Additional Information**
If the slicer executes the models in order of model height from lowest to highest, then it's possible to print larger models. A stretch goal would be to have a gantry width setting that allows to print one tall model on one half of the bed, then come forward to print another large model knowing that it won't bump into the previous model.

**Comment by rburema** [comment] 2020-06-04 09:48
Duplicate of https://github.com/Ultimaker/Cura/issues/6879 please discuss further there.

**Closed by rburema** 2020-06-04 09:48 UTC
