### ISSUE TITLE
[Warning] No default value set for:

### ISSUE THREAD

**Issue by CutAs** [Ultimaker/CuraEngine#1260] opened 2020-05-30 12:27 UTC
In my command line, I'm loading -j Ultimaker_S3.def.json and -j ultimaker_S3_left_extruder.def.json

Technically they are inheriting settings from generic ultimaker, fdmprinter, and fdmextruder

For some reason, if I load only fdmprinter and fdmextruder, I receive no warnings. If however, I try to override settings with ultimaker_s3 definitions, around 100 values are not read properly (warning: no default value). 

What am I doing wrong? Is there a way to read the def.json correctly? 

Thanks.

**Comment by nallath** [comment] 2020-06-02 11:53
The Ultimaker_s3 inherits some settings from other profiles. Did you check if the engine could also find those (eg; The Ultimaker_s3 inherits some stuff from "ultimaker.def.json", which in turn inherits from "fdmprinter.def.json")

I personally just use the CLI interface with fdmprinter.def.json, so I'm not sure if the inheritance bit works entirely how it should.

**Comment by CutAs** [comment] 2020-06-02 12:47
Hi, yes I did. In fact, slicer throws an error if one of the inherited files is missing from the path. So it gets the files but doesn't properly read the values.

**Comment by CutAs** [comment] 2020-06-02 12:55
My only workaround so far was to manually hard code the settings from ultimaker_s3.def.json (and extruder) to fdmprinter.def.json (and extruder) and then slice with those.

**Comment by Ghostkeeper** [comment] 2020-06-03 13:38
Duplicate of https://github.com/Ultimaker/CuraEngine/issues/1259, though you're now seeing a different setting that has a different outcome.

**Closed by Ghostkeeper** 2020-06-03 13:38 UTC
