### ISSUE TITLE
support area int not correct

### ISSUE THREAD

**Issue by zifengtayu** [Ultimaker/CuraEngine#329] opened 2016-04-26 03:06 UTC
![1](https://cloud.githubusercontent.com/assets/7849639/14805459/afc8cb70-0b9e-11e6-897c-09ec8b4754f1.png)
![2](https://cloud.githubusercontent.com/assets/7849639/14805460/afdf599e-0b9e-11e6-9ab9-3ac79fff337d.png)

the support erea isn't correct

**Comment by zifengtayu** [comment] 2016-04-26 03:10
version 2.1.0

**Comment by BagelOrb** [comment] 2016-04-26 07:39
Good catch!

Will fix this, hopefully soon. I'll have a chat with some of the frontend
guys.

What do you think is more intuitive: 90degrees = no support or 90 degrees =
support everywhere?
Op 26 apr. 2016 05:10 schreef "zifengtayu" <notifications@github.com>:

version 2.1.0

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Ultimaker/CuraEngine/issues/329#issuecomment-214594156>

**Comment by BagelOrb** [comment] 2016-04-26 08:32
I can't reproduce this.

Is the overhang still in the wrong place if you trigger a reslice (adjust a setting and adjust it back)?

What operating system do you have?

What graphics card do you have?

**Comment by zifengtayu** [comment] 2016-04-26 08:36
I will send you the model,

**Comment by zifengtayu** [comment] 2016-04-26 08:37
ListElement { text: "0.1"}

**Comment by zifengtayu** [comment] 2016-04-26 08:42
I have send the model to your width email

**Comment by BagelOrb** [comment] 2016-04-26 10:53
Thank you.

The support is actually not in the wrong areas. The placement is just very suboptimal for this particular model.

Note that the frontend only colors faces red which violate the overhang angle, while the engine will also look at edges and vertices which violate the overhang angle. My guess is that the rounded edges have some small overhang pieces which get joined downward into one large piece of support.

In order to understand the different types of overhang I've attached an STL which exemplifies them. [overhang_point_line_plane_straight.stl.txt](https://github.com/Ultimaker/CuraEngine/files/236417/overhang_point_line_plane_straight.stl.txt) 

In order to solve your problems we would need to revise the support generation system in a big way. We currently don't have the time to do that. However, it remains to be seen how problematic the new support system is; if there are too many problems we might revise it in a short while after all.

Closing this issue, since we're not going to fix this issue specifically in its own.

**Closed by BagelOrb** 2016-04-26 10:53 UTC
