### ISSUE TITLE
Start base infill from corner

### ISSUE THREAD

**Issue by Hokyjack** [Ultimaker/CuraEngine#123] opened 2014-08-27 23:01 UTC
Hello is it possible to make Cura start the filling of the first layer from one corner and end in the opposite corner when making rectangular shape? It would be raelly neat. Thanks!

**Comment by jmeosbn** [comment] 2015-03-24 17:25
Hi, I've just been looking at the code to see if I can improve the situation wrt point 1. but the codebase for this - and in particular, the math involved - is probably beyond my abilities and the time I can put into this.

I have made other changes not directly related to geometry/paths (PR forthcoming) but admit I had to give up on even finding the place where these decisions are made!  (Which is when I found this issue existed.) If known, it may be useful to link into the source where one might start looking for the above issues.

As to the first/original issue, is there a best effort that can be made for the majority of cases in which plain surfaces are currently printed in non-contiguous stripes?

**Comment by JustAnother1** [comment] 2015-03-24 20:53
@jmeosbn I also looked at the source. I think I saw something that might be it, but then again I might be totally wrong about it. Then I often run into the problem that finding ones way in a new project is rather hard to do.

Maybe you and me should start documenting what the parts that we can identify do? This way others might be able to fill the holes, and get started faster.

Would a pull request with such a document be accepted?

@BagelOrb  You basically say that directing your effort to other things will gain better results. Sop what if I want to wast some effort on this anyway? Would a "slow" solution have a chance to get included as a option that is disabled by default? Or is keeping the source code clean an the option count low more important than accepting such Pull requests?

**Comment by BagelOrb** [comment] 2015-03-25 10:20
Well, I would say that pathOrderOptimizer.cpp is a good starting point of course!

We are in hard need of documentation. But why and how would such documentation be in a separate document?
When documenting in-code, please use Doxygen style.
However, it would be a better idea to start documentation in the PinkUnicorn branch, since a lot of small documentation lines in the master branch will be hard to merge with that branch. (PinkUnicorn will become the main branch)
I recommend to either do documentation in the PinkUnicorn branch or don't document existing code at all just yet.

About the original problem: I just came to realize it should be quite easy.
Supposing for simplicity the infill is in the direction of the X axis:
For each part we store the point with the highest and the lowest Y coordinate and use these points as possible starting points of the part.
The partOrderOptimizer should then take only these two points into account when looking for the next closest part, and start at that point as well (perhaps first start with combing from the actually closest point on the polygon).
For infill at another angle we just use some tan(.) functions at the right places and BOOM, we're done!

That way the part order optimizer will be better for hardly any more computation time and we would also start the infill from a corner!

@JustAnother1 If the option is included as a setting, if it is well documented and it doesn't have too much code, I think a slow-computation-fast-printing solution would be very attractive.

**Comment by JustAnother1** [comment] 2015-03-26 22:22
Sorry for the delay. I have been on a business trip.

@BagelOrb "But why and how would such documentation be in a separate document?"

How could it possibly be within the code?

The point here is to distinguish between the types of documentation. There are a lot of different types of documentations.

If you need to explain a highly optimized/ complex/ mathematically tricky/ generally hard to understand part of the code then add comments to the code.

If you need to make other coders aware of certain pre- or post-conditions that need to be meet when calling a function. Or side effects of a function, then a doxygen comment is good. This also helps to understand the API of your modules.

So all these types can be in the code. But I think the problem addressed by me and @jmeosbn is not fixed by these types of documents.

The problem I face when I dig into a new(to me) open source project is that I find a lot of files. If I look into them I find a lot of functions that most of the time seem logical. One can understand what it is good for. One can identify certain parts, like logging/debugging, reading Files, addressing the EEPROM,..

But at the end after going through all the files you are left with a garage full of car parts and you have no Idea of how the car is supposed to look like.

With more investing and testing one will probably have a lot of Aha Events. (Aha this is supposed to go there, Yes that makes sense,..) And at the end you have a understanding of the project. This understanding might still be way off of what the Idea of the maintainer is. There are these situations of "It's not a bug! It's a feature!" and sometimes features get fixed.

So having a document (separate from the sources but as addition to the sources) that explains the basic things. Could help new people get into the source much faster. It could help get a common understanding of the intention of the code and it might even enable people to only familiarize themselves with a small part of the code and supply pull requests. The document would probably be something like this:

Cura Engine is a Slicer, It reads STL Files, created 2d slices with islands, and then creates paths for each island on each layer and together all these paths become the G-Code File.


This process is done int the following steps:
1. Read STl File
Is implemented in the files stl*.c in Folder foo/
2. triangles
Is implemented in bar.c
3. Layers
IS done in the layer_*() functions. and creates the data structures a, b and c and fills them with the correct data.
4. ...


Glossar:
These are the terms used in this code and their meaning:
Slide - One Layer,..
Island -
Triangle -
Model - 
...


Data Structures and what they represent
stlFile_type
triangle_type
2d_Layer_type
...


Other chapters
....

**Comment by BagelOrb** [comment] 2015-03-27 15:11
@JustAnother1 Oh you mean like that! I've been wanting this as well. I will start such documentation as part of the Doxygen generated help, as separate pages. You will most likely find them after today in CuraEngine/documentation/overview.md or something similar.

Can you respond to my ideas on the original topic?

**Comment by JustAnother1** [comment] 2015-03-28 12:37
@BagelOrb Yes I can. You refer to this:
> Supposing for simplicity the infill is in the direction of the X axis:
> For each part we store the point with the highest and the lowest Y coordinate and use these points 
> as possible starting points of the part.
> The partOrderOptimizer should then take only these two points into account when looking for the 
> next closest part, and start at that point as well (perhaps first start with combing from the actually 
> closest point on the polygon).
> For infill at another angle we just use some tan(.) functions at the right places and BOOM, we're 
> done!

This will probably help with a lot of simple shapes. But it might not work in more complex shapes. If you think about a Y shaped thing. It will start segment per segment in the right order on the bottom part. But in the upper part where you have the two arms this method will probably still jump from one arm to the next.

The best solution would be to do the infill in one go from the bottom of the Y up into one arm. Then doing the other arm. Using the "avoid moving over gaps and move only inside the model"-algorithm would make the segments of the "other" arm being far away and therefore would result in that best solution, right?

How about this: You start with the proposed top and bottom points. If you find a segment that is directly next to the previous then take that segment as the next segment. This will probably be the case most of the time. We would therefore get a very fast implementation. But if the next segment is farther away( = You need to add a G0 = Move without print)) then go for the "avoid moving over gaps" algorithm to find the next segment. In the Y example that will be needed probably not more than once (at the fork). As then the segments in the arm are again really close by. If you are lucky with the segments it might even not be needed. So as the algorithm will be used only very seldom I think the higher computing effort should be OK. But then we could also have this special treatment as part of the "slow computation for better quality" option.

And I will look out for the documentation. And hopefully I can send Pull Requests in the future.

**Comment by daid** [comment] 2015-03-30 08:32
Sorry for me bumping in here. (Main dev here, with too little time, sadly enough)

Been talking with @BagelOrb at the office. Problem with changing the start points of the perimeters to get slightly improved infill behavior is that it will effect the outer skin quality (more Z seams). It would be better to improve the PathOrderOptimizer for the infill lines itself instead of messing with the general one which will effect more then just the infill order.

**Comment by BagelOrb** [comment] 2015-03-30 12:24
@JustAnother1 
Some clarification:
My point wasn't about the order of lines within a part, but about which line of the infill to start with. 

My proposal was to start a layer part at a 'corner': if we start the perimeters at that point, then the infill will also get started there. This was what daid discarded as a bad idea because perimeters will start at different places each layer, depending on the infill angle.

Perhaps my ideas can still be applied to the infill alone, but this shouldn't happen in pathOrderOptimizer.cpp I think...

**Comment by JustAnother1** [comment] 2015-03-30 13:56
The "feature" that I dislike the most is that if CurAEngine tries to fill a circle it fills a stripe here then a stripe there and so on until the circle is filled.

A circle and a box as @Hokyjack requested could be filled in one go from one end to the other. If it is necessary to start the infill at a certain point to gain better quality, then the next best solution would be to fill circles and boxes in 2 phases. Stating from the Z-Scar point filling in one direction and then filling the rest.

I don't know which would be the best part of the code to fix this.

**Comment by BagelOrb** [comment] 2015-03-30 14:31
@JustAnother1
It seems your request is different from that of the original poster.
While the original poster wants to start at a corner, your request is about the order of infill lines.

If you print a rectangular shape the order of the lines is logical, but for a circle the order can be suboptimal. Fixing the order so that first al lines in one direction are printed in the logical order and then all lines perpendicular in sequence is certainly a good thing to have. However, we don't have a lot of time right now...

**Closed** 2015-04-02 14:33 UTC
