### ISSUE TITLE
MinGW build error on the CI server (requires update of libArcus on CI server)

### ISSUE THREAD

**Issue by bjude** [Ultimaker/CuraEngine#878] opened 2018-10-16 06:48 UTC
So this is caused by the CI server using a version of libArcus prior to this commit: https://github.com/Ultimaker/libArcus/commit/74e19d54cfeddee76d73a765387c8ef986740b06

When the functions in Arcus::Socket are not marked virtual we get a compile error for CuraEngine tests

**Comment by alekseisasin** [comment] 2018-10-16 08:48
We know about this, Libarcus needs to be updated on CI. We still keep the old one for building Cura 3.5 version.

**Comment by Ghostkeeper** [comment] 2018-12-21 12:20
The issue is fixed now. Sorry about this.

**Closed by Ghostkeeper** 2018-12-21 12:20 UTC
