### ISSUE TITLE
Shell before inner & outer walls on initial layer

### ISSUE THREAD

**Issue by jancoow** [Ultimaker/CuraEngine#1171] opened 2019-12-27 19:09 UTC
Hi.

Would it be possible to flip the printing order on the initial layer, so the shell gets printed before the inner and outer walls? I'm always having trouble printing small sequences of walls at the initial layer to stick properly to the bed. It would be great if the shell could be printed first, so it has a large area to stick tiny walls to. This would help the adhesion.

**Comment by Ghostkeeper** [comment] 2019-12-31 08:56
Did you try reducing the Small Feature Initial Layer Speed?

**Comment by jancoow** [comment] 2019-12-31 09:45
Yes I did, but it doesn't really help. I mostly have these issues with a big nozzle (0.8mm) and PETG. I've manually flipped the order in the gcode on the first layer and I was finally able to print a specific model, which didn't succeed before. This is because it's first doing the outer walls of a bunch of 3mm holes, where the path is way to short to stick properly.

**Comment by Ghostkeeper** [comment] 2020-01-02 10:21
See also https://github.com/Ultimaker/Cura/issues/6734.

**Comment by fvrmr** [comment] 2021-08-18 15:06
Closing this issue, since it is a duplicate of https://github.com/Ultimaker/Cura/issues/2988

**Closed by fvrmr** 2021-08-18 15:06 UTC
Labels: enhancement
