### ISSUE TITLE
Feature request: Use support for the Feature: "Make Overhang Printable"

### ISSUE THREAD

**Issue by TimoErdmann** [Ultimaker/CuraEngine#1168] opened 2019-12-21 10:33 UTC
Hello, 

i have stumbled over this paper: https://www.researchgate.net/publication/313546393_A_Level_Set_Based_Method_for_Fixing_Overhangs_in_3D_Printing

It is similar to the feature "Make Overhang Printable", but they are not manipulating the original part, but add a support strukture to catch up the overhangs. The benefits of this method is that it uses much less support structure than supporting these overhangs from the build plate (As you already intended by making it printable by changing the actual part). Additionally after removing the support structure you get your original part and not some defaced part. 

i don't know how much work it is to change the feature "Make Overhang Printable", but i let you know  that i am willing to test this new feature and support you as much as i can. 

PS: PM me if you are not able to get the paper

**Comment by Ghostkeeper** [comment] 2019-12-23 10:42
Duplicate of https://github.com/Ultimaker/Cura/issues/3465.

**Closed** 2019-12-23 10:46 UTC
