### ISSUE TITLE
15.09.90: "Connect Zig Zags" Setting Not Functioning

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/CuraEngine#265] opened 2015-10-15 13:55 UTC
I am seeing the support zigzags connected regardless of this setting's state. Is anyone else seeing this?

![image](https://cloud.githubusercontent.com/assets/12439543/10515741/75c92266-731a-11e5-9eaa-eb597788b3fc.png)

**Comment by BagelOrb** [comment] 2015-10-15 14:21
Perhaps the description is a bit unclear.

Normal ZigZags will look like 
``` 
..|""|..|""|..
```
While with Connect ZigZags they should look like
```
::|""|..|""|::
```
connected:
![curaengine_zigzags_connected](https://cloud.githubusercontent.com/assets/8895761/10516439/8cedbe8c-7358-11e5-9bb9-f16711dc31ed.png)
not connected:
![curaengine_zigzags_not_connected](https://cloud.githubusercontent.com/assets/8895761/10516438/8cecba78-7358-11e5-80cc-a680edc09b56.png)

On the right hand side of the triangle the setting seems to do what it's supposed to.

However, on the left hadn side of the triangle it doesn't seem to connect the end piece back to the rest.

**Comment by BagelOrb** [comment] 2015-10-15 14:25
The goal of the setting is to start on one of those straight scanlines instead of starting on the outer tip of the support, cause sometimes the outer tip starts in mid air.

**Comment by CCS86** [comment] 2015-10-15 15:11
Ah, I gotcha! 

What I had in my head, was probably more like "lines" vs "zig zags"

**Comment by BagelOrb** [comment] 2015-10-22 19:14
There's still a bug: the top picture shows a newly introduced line (bottom left) - away from the already connected lines, while the whole purpose was to get the top left connected back to the bottom left again.

The line piece from the top left to the bottom left is missing.

I think this is caused by the fact that that line is in the same direction as the vertical scanlines.

**Comment by BagelOrb** [comment] 2015-12-16 15:20
Closing this since the new bug report #287 is more accurate.

**Closed by BagelOrb** 2015-12-16 15:20 UTC
Labels: bug
