### ISSUE TITLE
Nozzle preheat added before start g-code

### ISSUE THREAD

**Issue by PatrikKopriva** [Ultimaker/CuraEngine#2099] opened 2024-06-18 18:31 UTC
**Application Version**
5.7.2

**Platform**
Windows

**Display Driver**
Not relevant

**Steps to Reproduce**
When I end up slicing the project and exporting the G-code, the exporter adds temperatures for the nozzle in front of my start G-code. I read that the Start g-code should contain brackets with the material temperature, which it does. The weird thing is that it is only adding temp for nozzle but it parses the bed temperature brackets.

Here is my g-code: 
```
`M104 S{material_print_temperature_layer_0}
M140 S{material_bed_temperature_layer_0} ; set final bed temp
M220 S100 ;Reset Feedrate
M221 S100 ;Reset Flowrate
M413 S0 ;Power Loss Recovery OFF

G28 ;Home
M420 S1; Use saved mesh leveling data
G92 E0 ;Reset Extruder
G1 X-3 Y0 Z0.28 F5000.0 ;Move to start position

M104 S{material_print_temperature_layer_0}
M109 S{material_print_temperature_layer_0}
M190 S{material_bed_temperature_layer_0} ; wait for bed and head

G1 Y90 E10 F1200 ; start purge
G92 E0; stop extruding
G1 Y120 F1800; finish purge
G1 Z2.0 F3000 ;Move Z Axis up`

```
**Actual Results**
In the G-code afterwards it adds:
`M104 S205
M105
M109 S205
M82 ;absolute extrusion mode
`
Before the rest of the G-code.

**Expected results**
It shouldnt add this.

**Additional Information**
N/A
[CE3V3SE_Stringing_Test.zip](https://github.com/user-attachments/files/15890998/CE3V3SE_Stringing_Test.zip)

**Comment by GregValiant** [comment] 2024-06-23 02:05
Thanks for the report.
This is a duplicate of [Cura #19204](https://github.com/Ultimaker/Cura/issues/19204).  You can unzip the attachment and install the "CuraPrependBugFix.py" post processor in the installation folder "C:\Program Files\UltiMaker Cura 5.7.2\share\cura\plugins\PostProcessingPlugin\ **scripts**".  It will be available under "Extensions/Post Processing/Modify Gcode" and then "Add script".  It will remove the temperature lines that are being erroneously added.
[CuraPrependBugFix.zip](https://github.com/user-attachments/files/15942259/CuraPrependBugFix.zip)

I'll mark this as a duplicate and close it as the Cura Team is aware of this bug.

**Closed by GregValiant** 2024-06-23 02:05 UTC
Labels: Type: Bug, Status: Duplicate
