### ISSUE TITLE
Concentric Top/Bottom Pattern Enhancement

### ISSUE THREAD

**Issue by Xisle** [Ultimaker/CuraEngine#235] opened 2015-08-17 22:00 UTC
The concentric top/bottom pattern is generated from outside to center sometimes and center to outside others. When the pattern starts in the center of a section it has nothing to connect to. It would be best if the concentric "rings" were always built from outside to center.

**Comment by BagelOrb** [comment] 2015-08-24 11:20
This will not be fixed soon; it sounds like an easier fix than it is.

**Comment by BagelOrb** [comment] 2015-11-04 12:54
This is a duplicate of https://github.com/Ultimaker/CuraEngine/issues/225

**Closed by BagelOrb** 2015-11-04 12:54 UTC
Labels: enhancement
