### ISSUE TITLE
Feature request: ability to apply monotonic skin only to outermost layer

### ISSUE THREAD

**Issue by richfelker** [Ultimaker/CuraEngine#1590] opened 2022-02-22 14:50 UTC
Monotonic skin fill is pretty much a must for surface quality, but a waste of travel time in all but the outermost layer, so it would be nice to be able to apply it only on the outermost layer.

For top skins this is already possible using 1 roofing layer, but I don't see any way to achieve the same for bottom layers. I think this is fairly low priority because there are already reasons you're likely to have poor surface quality on non-initial bottom layers with nontrivial geometry, but I'm posting it for completeness.

**Comment by fvrmr** [comment] 2022-02-25 15:02
Hi @richfelker thank you for your request. This is as a duplicate of https://github.com/Ultimaker/Cura/issues/10617
I will close this issue since it is a duplicate.

**Closed by fvrmr** 2022-02-25 15:02 UTC
