### ISSUE TITLE
Something strange hole at wall

### ISSUE THREAD

**Issue by joonghochoe** [Ultimaker/CuraEngine#1329] opened 2020-09-23 07:23 UTC
**Application Version**

master version

**Platform**

windows 10

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**

1. load housing.3mf
2. change "Maximum Resolution" to 0.2
3. change "Maximum Travel Resolution" to 0.6
4. change "Maximum Deviation" to 0.1
5. slice
 
**Actual Results**

there is some strange hole at wall

**Expected results**

no hole

**Additional Information**

![화면 캡처 2020-09-23 160235](https://user-images.githubusercontent.com/39176348/93979280-19fc5b00-fdb8-11ea-9d41-dc44c7dcb444.jpg)

3d model file is

[UMS5_housing.zip](https://github.com/Ultimaker/CuraEngine/files/5266259/UMS5_housing.zip)

there is no strange hole in 4.7.1 version. It causes abnormalities from the cura engine merged version on September 17, "Merge pull request #1321 from Ultimaker/CURA-7709_simply_leaves_tiny_segments"

**Comment by Ghostkeeper** [comment] 2020-09-23 08:32
I'd be surprised if #1321 itself would cause this since that algorithm only adjusts the vertices of a contour. It's not able to create new contours.
Could it be changes we made to stitching a few days earlier? https://github.com/Ultimaker/CuraEngine/commit/3b310a5ace1ac40ed77a21e6feb724295f8fcabc We already have an incoming fix for that here: https://github.com/Ultimaker/CuraEngine/pull/1325

**Comment by joonghochoe** [comment] 2020-09-24 23:12
A similar problem appears in the new master version(Sep.24).
Resolution Setting Changed of master version :
![skin_hole](https://user-images.githubusercontent.com/39176348/94208981-1d9df800-ff06-11ea-86a6-5cea0191b8c5.jpg)

Resolution Setting Default of master version:
![skin_nohole](https://user-images.githubusercontent.com/39176348/94208993-2262ac00-ff06-11ea-98b9-5e8a99db4f33.jpg)

Resolution Setting Changed of 4.7.1 version:
![skin_nohole_471](https://user-images.githubusercontent.com/39176348/94209127-7a99ae00-ff06-11ea-952b-8ec2eab9769c.jpg)

Used 3D model 3mf file:
[UMS3_Compressor_Wheel_hole.zip](https://github.com/Ultimaker/CuraEngine/files/5279695/UMS3_Compressor_Wheel_hole.zip)

**Comment by Ghostkeeper** [comment] 2020-09-25 09:08
That project file reproduces the problem for me as well. Since the fix for stitching was already merged in #1325 I don't think that was the issue. We'll investigate.

**Comment by konskarm** [comment] 2020-09-30 13:46
Can you try with this fix https://github.com/Ultimaker/CuraEngine/pull/1336? Trying it locally, I see that the weird artifacts are no longer generated after changing the Maximum Resolution and Deviation.

**Comment by joonghochoe** [comment] 2020-10-05 03:57
The problem doesn't seem to occur in the new master version. Thanks.

**Closed** 2020-10-05 07:58 UTC
