### ISSUE TITLE
Gaps in sliced output

### ISSUE THREAD

**Issue by daniel-starke** [Ultimaker/CuraEngine#1424] opened 2021-02-27 20:54 UTC
**Application Version**
4.8.0

**Platform**
Windows 7 Professional SP1 x64

**Display Driver**
4.1.0 NVIDIA 445.75

**Steps to Reproduce**
Slice the attached project.
[piece-hole.3mf.zip](https://github.com/Ultimaker/CuraEngine/files/6055373/piece-hole.3mf.zip)

**Actual Results**
Gaps in the model are visible in the preview.
![gaps](https://user-images.githubusercontent.com/22841069/109399904-efee2c80-7945-11eb-8735-00b0ba713eed.png)

**Expected results**
The model has real round holes in the middle and no gaps in the wall.

**Additional Information**
This issue did not occur with Cura 3.6.

**Comment by fvrmr** [comment] 2021-03-02 14:47
Hi @daniel-starke thank you for your report.
If I slice your model in our Arachne release, it doesn't happen. 
![Screenshot (100)](https://user-images.githubusercontent.com/77000924/109665271-48a00e00-7b6e-11eb-9f94-36cad6b4b4e9.png)

Read [here](https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_alpha) more about Arachne. 

I will close this issue because it is solved, but feel free to reach out if you have more questions.

**Closed by fvrmr** 2021-03-02 14:47 UTC

**Comment by Ghostkeeper** [comment] 2021-03-05 13:24
This is caused by the Maximum Resolution setting. Lowering that to a bit finer resolution fixes the issue.
