### ISSUE TITLE
Multi Extrusion - Prime tower too dense

### ISSUE THREAD

**Issue by Riffo** [Ultimaker/CuraEngine#93] opened 2014-05-10 23:55 UTC
Doing dual or triple extrusion the priming tower is too dense causing prints to fail and put strain on printer.  The primeing tower is soon taller than the print itself which stops the priming from working due to the hotend being pressed hard against prime tower.  When printing a layer with a single colour all 3 filaments are still priming, would be far better for just the filament in use to do a fine layer on tower to maintain it until required.

Printer is i3 with triple extruder.  3 filaments share a single hotend, swapping by massive retraction and then need to purge about 125mm3 to have clear hotend.   can use smaller tower with larger prints though being so dense it gets knocked off plate.  For a test just did 4mm high basic 3 colour print, priming tower is measuring 5.7mm high for 3 colours,  Do acheive triple extrusion am first doing dual merge, then selecting that and doing another dual merge with 3rd colour part.

**Comment by Riffo** [comment] 2015-02-23 06:38
Still have this issue in latest version of cura.  Any chance the extrusion rate could be reduced when doing priming with 3 colours?  am happy to make a bigger tower if required, just frustrating not being able to use it, trying to do off bed priming still for now to be able to use

**Comment by daid** [comment] 2015-02-23 08:48
I'm sorry, but multi extrusion simply does not has the focus right now.

**Comment by Kulitorum** [comment] 2015-03-22 10:54
i guess my problem, "Wipetower position" is a duplicate of this.

Riffo, did you find another slicer thats better for this? - I'm going with kisslicer for now, although I have retraction problems.

CuraEngine: https://www.youtube.com/watch?v=Snej7wkmZg8

**Comment by BagelOrb** [comment] 2015-03-25 08:42
It seems as though the prime tower code depends on there being only two colors. My guess is therefore that the wipe tower in your clip has 1.5 times the volume it should have.

With two colors, we switch color once every layer, and so the wipe tower gets one layer each switch. With X colors, we switch (X-1) times every layer.

The problem could be solved by turning down the extrusion rate for the wipe tower, but then we would also need to adjust for the layer thickness.
I think a better solution would be to have (X-1) separate wipe towers.

This shouldn't be too hard to code; maybe someone else can find the time?

**Comment by wawanbreton** [comment] 2024-03-22 09:34
Hi @Riffo, I'm closing this ticket as we have integrated a new prime tower that addresses the issue you pointed out. You can try it on the last 5.7 beta.

**Closed by wawanbreton** 2024-03-22 09:34 UTC
Labels: Type: Bug, Multi-extrusion
