### ISSUE TITLE
[5.x.x] CuraEngine crashes when slicing walls

### ISSUE THREAD

**Issue by Dogm** [Ultimaker/CuraEngine#1895] opened 2023-07-05 12:19 UTC
**Application Version**
all 5.x.x

**Platform**
Tested on Windows but most likely relevant for all platforms

**Steps to Reproduce**
1) use model.stl - (need rename jpg to stl for correct file format)
![model stl](https://github.com/Ultimaker/CuraEngine/assets/13658104/5f597b67-f994-45fe-b8aa-fa46ecdeccb4)

2) move model on platform
x += 1.5005f
y += 1.5005f
z += -0.122840881f

3) set line width = 5.6 mm, layer height 0.2 mm

SlicerProcess will crashes with reporting progress of generating WallToolPaths (i have this one in 13 layer (~2.6mm from bottom))

Crush in \src\SkeletalTrapezoidationGraph.cpp

```
void SkeletalTrapezoidationGraph::collapseSmallEdges(coord_t snap_dist) {
...
        //  o-o
        //  | | > collapse sides
        //  o o
        if (should_collapse(quad_start->from, quad_end->to) && should_collapse(quad_start->to, quad_end->from))
        { // Collapse start and end edges and remove whole cell
        ...
            quad_start->twin->twin = quad_end->twin;
            quad_end->twin->twin = quad_start->twin;  // <------ quad_end->twin = null
        ...
        }
...
}
```

**Comment by Dogm** [comment] 2023-07-05 15:51
Any ideas how to fix this bug?

**Comment by jellespijker** [comment] 2023-07-05 17:52
this is the infamous slicing crash that you encounter. It is a complex problem to solve, what often helpa is rotating the model and slice again. 


@MariMakes do we have a Cura issue where we can link this issue?

**Comment by Dogm** [comment] 2023-07-07 12:50
Have same problem sometimes on generate infill walls (Lines pattern)  8(

**Comment by jellespijker** [comment] 2023-07-11 19:54
hi @Dogm I'm closing this issue as a duplicate of Ultimaker/Cura#12019

**Closed** 2023-07-11 19:55 UTC
