### ISSUE TITLE
Bug? Bridged inner walls appear narrower than normal inner walls

### ISSUE THREAD

**Issue by Sophist-UK** [Ultimaker/CuraEngine#1392] opened 2021-01-09 18:41 UTC
**Application Version**
4.8.0

**Platform**
Windows 10 64-bit

**Steps to Reproduce**
1. Nozzle 0.4mm. Outer walls 0.4mm. Inner walls 0.5mm (line-width wider than nozzle results in filament being squished and better fusion).
2. Bridge over support.
![image](https://user-images.githubusercontent.com/3001893/104106237-43c88780-52ac-11eb-8eea-ced73b693b56.png)

**Actual Results**
Normal inner walls are fused to each other and to outer walls.
Bridged inner walls have gaps between each other and with outer walls.

**Expected results**
Bridged inner walls are fused to each other and to outer walls.

**Additional information**
This could simply be because the outer walls are not fixed as firmly to the layer below (or since I have one layer gap, 2 layers below), and so inner walls are not squished the same), but this doesn't seem intuitive. With a line width of 125% of nozzle width, material flow should be 125% too - and I wonder whether bridged extrusions are missing this multiplier.

**Comment by fvrmr** [comment] 2021-01-15 10:43
Can you share your project file? So I can reproduce this.

**Comment by Sophist-UK** [comment] 2021-01-15 14:17
[TEST.zip](https://github.com/Ultimaker/CuraEngine/files/5820988/TEST.zip)
Sorry - I had already zipped it up - I forgot to attach it to the original issue.

**Comment by Ghostkeeper** [comment] 2021-01-18 17:22
It's nice how we can nowadays just load your project files in Cura since the DiscoEasy definition is built-in now :) You've reported a lot of bugs so it makes things a lot easier.

I think what you're seeing is the result of Compensate Wall Overlaps. It's not just happening in the bridging lines, but also in the non-bridging part further out. Compensate Wall Overlaps finds the walls that overlap and reduces the flow rate of one of them (whichever prints last). It doesn't adjust the position of that line though, expecting the material to flow over to fill the gap. So in theory it still partially overlaps with the neighbouring wall and then has an equal-sized gap on the other side. In practice there will not be a gap since the required material is still extruded very close to the gap.

However I can imagine that this doesn't work very well when bridging. There is no counterpressure then to force the material to flow over into the gap.

This problem is resolved in our [experimental version with variable line widths](https://github.com/Ultimaker/Cura/releases/tag/Arachne_engine_alpha) which completely removed that algorithm in favour of just never creating overlapping walls any more. So once Ultimaker/CuraEngine#1210 is merged, this problem should be removed as well.

**Comment by Ghostkeeper** [comment] 2021-12-14 11:12
This is fixed by https://github.com/Ultimaker/CuraEngine/pull/1210.

**Closed by Ghostkeeper** 2021-12-14 11:12 UTC
